### ISSUE TITLE
Restore `start/stop` Unit Test

### ISSUE THREAD

**Issue by zixia** [linyimin-bupt/wechaty-puppet-ioscat#4]

**Comment by linyimin-bupt** [comment]
In local environment, the test pass.While in Travis-ci, test Node10 can pass, but the node 9 is error.
The reason is:

TAP version 13
# PuppetMock restart without problem
09:12:24 ERR TypeError: task.finally is not a function 
not ok 1 Error: cache not exist
  ---
    operator: fail
    at: Object.<anonymous> (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/src/puppet-ioscat.spec.ts:23:7)
    stack: |-
      Error: Error: cache not exist
          at Test.assert [as _assert] (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/node_modules/tape/lib/test.js:76:32)
          at Object.<anonymous> (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/src/puppet-ioscat.spec.ts:23:7)
          at Generator.throw (<anonymous>)
          at rejected (/home/travis/build/linyimin-bupt/wechaty-puppet-ioscat/src/puppet-ioscat.spec.ts:6:65)
          at <anonymous>
  ...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by linyimin-bupt** [comment]
OK
